### ISSUE TITLE
Uploading of notebook and data does not work

### ISSUE THREAD

**Issue by Chiil** [2i2c-org/pilot#5]
I am trying to upload one of my notebooks and the data to the pilot hub, but there seems to be no file transfer.

**Comment by choldgraf** [comment]
could you try https://2i2c.org/pilot/use.html#include-content-in-your-hub ?

**Comment by choldgraf** [comment]
also you should have an upload button here:

![image](https://user-images.githubusercontent.com/1839645/94964988-84e01d00-04af-11eb-8f0b-711dc3118423.png)

**Comment by Chiil** [comment]
I used the upload button, I see that the transfer has started but after that I do not see the bar filling as usual:

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/110313/94965131-37899d00-04fb-11eb-9b4d-e66108512810.png">

**Comment by choldgraf** [comment]
Hmm weird, it just worked for me. Try an nbgitpuller link and we can debug this later?

**Comment by Chiil** [comment]
The nbgitpuller works great. I have a notebook now, and the notebook can load or install the required packages. To test my full notebook, I need the upload function to work, because I cannot put our data files on GitHub.

**Comment by choldgraf** [comment]
Makes sense. I guess you could try restarting your server and see if it works after doing so. Is the dataset particular large or anything?

**Comment by Chiil** [comment]
It doesn’t help. None of the uploads work, independent of file size. I can select the file, press upload, and then it stalls.

**Comment by choldgraf** [comment]
That's bizarre, I will try to look into it though am on baby duty right now!

**Comment by choldgraf** [comment]
I just tried starting a server as your user and the upload worked fine as well...so I wonder if this could be some kind of oversees usage issue? Either way, perhaps we can find a time to debug together tomorrow morning, or perhaps @yuvipanda has ideas for what's up 

another thing you could try is to use jupyterlab (just replace `/tree` with `/lab` in the URL) by dragging and dropping the files into there.

**Comment by Chiil** [comment]
The lab gives me the same error. 
<img width="296" alt="image" src="https://user-images.githubusercontent.com/110313/94984737-bdcfce80-054f-11eb-83f1-cbb244a7f156.png">

**Comment by choldgraf** [comment]
ahh yeah I bet you're right that the file size is a bottleneck here. I just tried uploading a larger file and it didn't work as well 👍 . It sounds like a 413 error suggests this too: https://confluence.atlassian.com/jirakb/http-error-413-request-entity-too-large-failure-when-attaching-files-693900009.html#:~:text=A%20413%20error%20indicates%20that,willing%20or%20able%20to%20process.

Probably something configurable on the Jupyter server side.

In the meantime as a short-term solution to keep demo-ing, you could try to add a cell at the top of the notebook session that downloads this. e.g.:

```
!wget https://my-large-file
```

since persistent storage isn't turned on yet, you may wanna do something like this anyway to avoid having to manually upload each time.

**Comment by Chiil** [comment]
This works. My notebook runs fine and ends up with 997 MB of memory usage :). Experience has been good. Missing packages install well without trouble. I have one notebook, which is currently running, that requires `ffmpeg` to create movies. Would it be possible to install that?

**Comment by yuvipanda** [comment]
The upload limit should be fixed now! I'm working on getting ffmpeg installed.

Excited to put this into production! \o/

**Comment by Chiil** [comment]
It still does not work here? I am trying to upload a 3.6 MB notebook and 50 MB of data and the same thing as before happens.

**Comment by yuvipanda** [comment]
@Chiil hmm, am investigating again now.

**Comment by yuvipanda** [comment]
@Chiil try now?

**Comment by Chiil** [comment]
Now it works! Great.

**Comment by yuvipanda** [comment]
Great! ffmpeg should also be there now.

**Comment by Chiil** [comment]
It doesn't work, maybe the script cannot find the executable.

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-10-590854a5f902> in <module>
     13                                frames=h_prime_out.shape[0], interval=40, blit=True)
     14 
---> 15 HTML(anim.to_html5_video())

/opt/conda/lib/python3.8/site-packages/matplotlib/animation.py in to_html5_video(self, embed_limit)
   1314                 # We create a writer manually so that we can get the
   1315                 # appropriate size for the tag
-> 1316                 Writer = writers[mpl.rcParams['animation.writer']]
   1317                 writer = Writer(codec='h264',
   1318                                 bitrate=mpl.rcParams['animation.bitrate'],

/opt/conda/lib/python3.8/site-packages/matplotlib/animation.py in __getitem__(self, name)
    164         if self.is_available(name):
    165             return self._registered[name]
--> 166         raise RuntimeError(f"Requested MovieWriter ({name}) not available")
    167 
    168 

RuntimeError: Requested MovieWriter (ffmpeg) not available
```

**Comment by choldgraf** [comment]
I wonder if you could try installing `ffmpeg` from conda until we get it installed on the base image:

```
conda install -c conda-forge ffmpeg
```

**Comment by yuvipanda** [comment]
I think it should be present, you might have to try starting / stopping your server. I can see it in my server

![Uploading image.png…]()

**Comment by choldgraf** [comment]
ah yes - stopping/starting made it work for me

**Comment by Chiil** [comment]
It all works. My three notebooks that I tested all work out fine, and the data is persistent. Great 👍.

**Comment by choldgraf** [comment]
![](https://media.giphy.com/media/tIR7TiaIaXih2AGStY/giphy.gif)

**Comment by choldgraf** [comment]
gonna close this one as I think it's finished 👍
